on:
    workflow_dispatch:
    push:
        branches:
            - master

jobs:
    test:
        name: Install and Build with node on ubuntu-latest
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js 20.x
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x

            - name: npm install and build
              run: |
                  npm install
                  npm run winBuild --if-present
                  echo Build ready for deployment!

            - name: Upload build artifact
              uses: actions/upload-artifact@v3
              with:
                  name: build
                  path: dist

            - name: Install Netlify CLI and deploy to prod
              run: |
                  npm install netlify-cli --save-dev 
                  netlify deploy --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --dir=dist --prod
